### ISSUE TITLE
Suggestion: Allow backup/restore of deck ease factors

### ISSUE THREAD

**Issue by brownbat** [RisingOrange/Reset-Ease-Automatically#1]
Users sometimes want to save ease factors on a deck, maybe to return to a prior state after trying out a new add on.

Your code here is very clean, seems like it could be easily expanded to allow people to backup and restore deck ease settings to previous versions if you wanted. You could just add these functions to reset_ease.py and have the basic framework there:

```python
def store_ease(deck_name):
    '''For some deck `deck_name`, returns a dictionary linking card id keys to
    ease factors.
    '''
    ease_backup = {}
    card_ids = mw.col.find_cards(f'deck:"{deck_name}"')
    for card_id in card_ids:
        card = mw.col.getCard(card_id)
        ease_backup[card_id] = card.factor
    return ease_backup


def restore_ease(deck_name, backup):
    '''For deck `deck_name` and `backup`--a dictionary linking card id keys to
    ease factors--set the ease factors of the cards in the deck to the ease
    factors provided in `backup`.
    '''
    card_ids = mw.col.find_cards(f'deck:"{deck_name}"')
    for card_id in card_ids:
        card = mw.col.getCard(card_id)
        card.factor = backup.get(card_id, card.factor)
        card.flush()
```

The only questions would be where you want to store the backups, how many backups you want to store, how to let users name and recall those backups and specify that they're trying to backup or restore rather than reset ease...

Ok there are a lot of UX questions.

But what do you think about supporting that in general? Makes the add on a little more complex, but could help a ton of people. 

I'd be happy to help if you know how you would want it to look.

**Comment by brownbat** [comment]
Great project btw, definitely one I'll use, even if you don't go with the suggestion.

**Comment by RisingOrange** [comment]
Hmm, sounds like a good idea. Also nice to hear that someone finds my project useful.
Do you have think it would be sufficient to let the users backup and restore ease factors manually?
I imagine adding two actions to the menu: "Export ease factors" and "Import ease factors".
Clicking on them brings up a file picker to let users save/restore (from) the backup file where they want, the default location being a folder named "ease factor backups" inside the users Anki folder.
The default name of the backups are like this:
If you have specified one deck in the preferences, the name is something like
"ease_factors_[deck_name]_[datetime]"
If there are multiple decks:
"ease_factors_[amount_of_decks]_decks_[datetime]"

The backup file contains only the ease factors of the cards in decks that are specified in the preferences, not of all cards in the collection, so other decks are not affected by a restore.

On second thought, maybe separate backups for each deck would be better, so that the user can restore them selectively?

What do you think?

**Comment by brownbat** [comment]
Definitely agree it should be manual only -- let people control the files and restoration.

It might actually be easier to add it in the individual deck settings rather than tie it to your main config window at first.

Like so... 

```python
from aqt.gui_hooks import deck_browser_will_show_options_menu

def on_deck_browser_will_show_options_menu(menu, deck_id):
    backup_action = menu.addAction("Backup Ease Factors")
    backup_action.triggered.connect(lambda _, did=deck_id: backup_ease_factors(did))
    restore_action = menu.addAction("Restore Ease Factors")
    restore_action.triggered.connect(lambda _, did=deck_id: restore_ease_factors(did))


deck_browser_will_show_options_menu.append(on_deck_browser_will_show_options_menu)
```

Ok, I should just do a PR with a working demo instead of piecemealing this together in comments. 

I just haven't done file pickers yet, so not sure if I can glue this all together.

I think your default settings name is the right one.
ease_factors_[deck_name][datetime]

If this works you might want to circle back with a way to save ease factors in multiple decks at once, but just getting the per deck version working first will be easiest and gets people 90% of the way there.

**Comment by RisingOrange** [comment]
Great!
I like the idea of putting the backup/restore action in the deck settings.
I'm new to coding UI/Qt, but the file picker should be not too hard to implement using QFileDialog.

**Comment by brownbat** [comment]
I'm going to pull the import and export options into my ease adjustment add on too, since a lot of people have asked for that. I'll look around at the best way to avoid collisions... I think worst case if someone has both add-ons installed they might get duplicate menu options. I'll give mine distinctive names just in case.

I wonder if I can add a submenu...

**Comment by RisingOrange** [comment]
One could also put the code in a seperate addon just for importing and exporting ease options, but I'm not sure if it is worth it.
